# YAML Linting Configuration
# Used by lint-staged for YAML file validation

extends: default

rules:
  # Line length - allow longer lines for URLs and complex configs
  line-length:
    max: 200
    level: warning
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: true

  # Indentation - consistent 2-space indentation
  indentation:
    spaces: 2
    indent-sequences: true
    check-multi-line-strings: false

  # Document markers - allow files without explicit document markers
  document-start: disable
  document-end: disable

  # Truthy values - allow various truthy representations
  truthy:
    allowed-values: ['true', 'false', 'yes', 'no', 'on', 'off']
    check-keys: false

  # Comments - require space after #
  comments:
    require-starting-space: true
    ignore-shebangs: true
    min-spaces-from-content: 1

  # Brackets - allow inline flow sequences
  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 1

  # Braces - allow inline flow mappings
  braces:
    min-spaces-inside: 0
    max-spaces-inside: 1

  # Colons - standard spacing
  colons:
    max-spaces-before: 0
    max-spaces-after: 1

  # Commas - standard spacing
  commas:
    max-spaces-before: 0
    min-spaces-after: 1
    max-spaces-after: 1

  # Hyphens - standard list markers
  hyphens:
    max-spaces-after: 1

  # Empty lines - allow some flexibility
  empty-lines:
    max: 2
    max-start: 0
    max-end: 1

  # Key duplicates - disallow
  key-duplicates: enable

  # Key ordering - don't enforce
  key-ordering: disable

  # New lines - require final newline
  new-line-at-end-of-file: enable
  new-lines:
    type: unix

  # Octal values - allow
  octal-values:
    forbid-implicit-octal: true
    forbid-explicit-octal: false

  # Quoted strings - don't enforce
  quoted-strings: disable

  # Trailing spaces - disallow
  trailing-spaces: enable

# Ignore generated files and large config files
ignore: |
  node_modules/
  .git/
  helm/*/charts/
  **/Chart.lock
  **/requirements.lock
